on:
  workflow_dispatch:
  push:
    branches: 
      - main
      - prerelease
  workflow_call:
    inputs:
      ref: 
        required: true
        description: 'The ref to trigger the workflow on'
        type: string
      prerelease:
        required: true
        description: 'Whether to deploy prerelease or release site'
        type: boolean
        default: false

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # if called from workflow_call event, checkout the ref otherwise use default
          ref: ${{ inputs.ref || '' }}

      - name: Get latest pre-release from github
        id: github-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo version=$(gh api repos/quarto-dev/quarto-cli/releases | jq -r 'map(select(.prerelease)) | first | .tag_name | sub("^v";"")') >> "$GITHUB_OUTPUT"

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: ${{ steps.github-release.outputs.version }}

      - name: Render 
        uses: quarto-dev/quarto-actions/render@v2

      - name: Publish release website
        # Only do this step if the branch is main or workflow is called for release deploy
        if: ${{ !inputs.prerelease || github.ref == 'refs/heads/main'}}
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          render: false

      - name: Deploy Prerelease website to Netlify
        # Only do this step if the branch is prerelease or workflow is called for prerelease deploy
        if: ${{ inputs.prerelease || github.ref == 'refs/heads/prerelease' }}
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v3
        env:
          NETLIFY_SITE_ID: 2a3da659-672b-4e5b-8785-e10ebf79a962
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
          publish-dir: './_site'
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: |
            Deploy from GHA: ${{ format('manual from {0} at commit {1}', github.ref_name, github.sha) }}
          alias: prerelease
          # these all default to 'true'
          enable-pull-request-comment: false
          enable-commit-comment: false
          enable-commit-status: true
          overwrites-pull-request-comment: false
        timeout-minutes: 1